module.exports = {
  "rules": {
    /*quotes*/
    "string-quotes": "double",
    "color-hex-case": "lower",
    "color-hex-length": "short",
    "color-no-invalid-hex": true,
    "color-no-named": true,
    "number-leading-zero": "never",
    "number-no-trailing-zeros": true,
    "number-zero-length-no-unit": true,
    "function-calc-no-unspaced-operator": true,
    "function-comma-newline-after": "never-multi-line",
    "function-comma-newline-before": "never-multi-line",
    "function-comma-space-after": "always",
    "function-comma-space-before": "never",
    "function-linear-gradient-no-nonstandard-direction": true,
    "function-parentheses-space-inside": "never",
    "function-whitespace-after": "always",
    /*url*/
    "function-url-quotes": "double",
    "value-list-comma-newline-after": "never-multi-line",
    "value-list-comma-newline-before": "never-multi-line",
    "value-list-comma-space-before": "never",
    "declaration-bang-space-after": "never",
    "declaration-bang-space-before": "always",
    "declaration-colon-newline-after": "always-multi-line",
    "declaration-colon-space-before": "never",
    "declaration-block-semicolon-newline-after": "always",
    "declaration-block-semicolon-newline-before": "never-multi-line",
    "declaration-block-semicolon-space-before": "never",
    "block-closing-brace-newline-after": "always",
    "block-closing-brace-newline-before": "always",
    "block-no-empty": true,
    "block-opening-brace-newline-after": "always",
    "block-opening-brace-space-before": "always",
    "selector-combinator-space-after": "always",
    "selector-combinator-space-before": "always",
    "selector-list-comma-newline-after": "always",
    "rule-no-duplicate-properties": true,
    "declaration-block-no-single-line": true,
    "declaration-block-single-line-max-declarations": 1,
    "rule-trailing-semicolon": "always",
    "media-feature-colon-space-after": "always",
    "media-feature-colon-space-before": "never",
    "media-feature-range-operator-space-after": "always",
    "media-feature-range-operator-space-before": "always",
    "media-query-parentheses-space-inside": "never",
    "indentation": 4,
    "max-empty-lines": 1,
    "declaration-colon-space-after": "always"
  }
}

